In [11]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/6b/fb/bb613f4122c310a13ec67585c70e14b03bfc7ebabd24f4d5138b97371d7c/numpy-2.3.1-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------- ------------------------- 20.5/60.9 kB 65.2 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/60.9 kB 93.5 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 115.5 kB/s eta 0:00:01
     -------------------------------------- 60.9

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [14]:
lst =[1,2,3,4,5,6]
arr =np.array(lst)

In [15]:
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
arr =np.array([1,2,3,4,5,66,7,])

In [18]:
arr

array([ 1,  2,  3,  4,  5, 66,  7])

In [19]:

lst =[1,2,3,4,5,6]
print("types of list",type(lst))
arr =np.array(lst)
print(arr)
print("types of array",type(arr))

types of list <class 'list'>
[1 2 3 4 5 6]
types of array <class 'numpy.ndarray'>


In [20]:
arr =np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
arr =np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros((5,10))        # 5 rows 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr =np.linspace(1,10,5)        # 5 elements bw 1-10 with same difference
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
## ls array convert into 22d array
arr =np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [7]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [8]:
arr =np.random.randint(1,5,9)
arr

array([3, 3, 4, 1, 1, 1, 3, 2, 4], dtype=int32)

In [9]:
arr =np.random.random(10)
arr

array([0.87315556, 0.8824643 , 0.44337635, 0.16982011, 0.09460489,
       0.83314864, 0.57470447, 0.99930229, 0.07013682, 0.62745035])

In [12]:
arr =np.random.random((5,10))
arr

array([[0.9705422 , 0.0849363 , 0.69974478, 0.58506682, 0.67273881,
        0.51891327, 0.23173355, 0.99163562, 0.95290412, 0.39851224],
       [0.9087    , 0.10074478, 0.09205919, 0.56699592, 0.02313767,
        0.53311028, 0.64082912, 0.28936402, 0.10678472, 0.02926003],
       [0.41955043, 0.68430188, 0.53377889, 0.36470979, 0.04193901,
        0.20823459, 0.45854184, 0.12569403, 0.60869826, 0.0758576 ],
       [0.80906737, 0.14244809, 0.1321203 , 0.10274602, 0.10414804,
        0.61652363, 0.48863436, 0.28253762, 0.99540417, 0.78037943],
       [0.07337063, 0.07706326, 0.66055634, 0.07284624, 0.15645654,
        0.38525752, 0.37796512, 0.80765566, 0.18914824, 0.56010084]])

In [32]:
arr = np.arange(60).reshape(12, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print("data types",arr.dtype)
print("number of dimensions",arr.ndim)


shape of array (12, 5)
size of array 60
data types int64
number of dimensions 2


In [34]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [75]:

arr = np.arange(60).reshape(12, 5)
print(arr.shape)


(12, 5)


In [71]:
arr.T

array([1, 2, 3, 5, 6, 9])

In [73]:
import numpy as np

arr = np.arange(60).reshape(12, 5)
print(arr.T.shape)


(5, 12)


In [77]:
arr[5]

array([25, 26, 27, 28, 29])

In [78]:
arr[2]

array([10, 11, 12, 13, 14])

In [13]:
arr[0:12]

array([[0.9705422 , 0.0849363 , 0.69974478, 0.58506682, 0.67273881,
        0.51891327, 0.23173355, 0.99163562, 0.95290412, 0.39851224],
       [0.9087    , 0.10074478, 0.09205919, 0.56699592, 0.02313767,
        0.53311028, 0.64082912, 0.28936402, 0.10678472, 0.02926003],
       [0.41955043, 0.68430188, 0.53377889, 0.36470979, 0.04193901,
        0.20823459, 0.45854184, 0.12569403, 0.60869826, 0.0758576 ],
       [0.80906737, 0.14244809, 0.1321203 , 0.10274602, 0.10414804,
        0.61652363, 0.48863436, 0.28253762, 0.99540417, 0.78037943],
       [0.07337063, 0.07706326, 0.66055634, 0.07284624, 0.15645654,
        0.38525752, 0.37796512, 0.80765566, 0.18914824, 0.56010084]])

In [23]:
arr[0]=100

In [24]:
arr

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02],
       [9.08699999e-01, 1.00744783e-01, 9.20591884e-02, 5.66995919e-01,
        2.31376699e-02, 5.33110276e-01, 6.40829121e-01, 2.89364019e-01,
        1.06784720e-01, 2.92600326e-02],
       [4.19550425e-01, 6.84301883e-01, 5.33778889e-01, 3.64709794e-01,
        4.19390052e-02, 2.08234589e-01, 4.58541842e-01, 1.25694026e-01,
        6.08698261e-01, 7.58575992e-02],
       [8.09067371e-01, 1.42448089e-01, 1.32120305e-01, 1.02746018e-01,
        1.04148042e-01, 6.16523630e-01, 4.88634364e-01, 2.82537615e-01,
        9.95404169e-01, 7.80379428e-01],
       [7.33706288e-02, 7.70632585e-02, 6.60556345e-01, 7.28462353e-02,
        1.56456542e-01, 3.85257518e-01, 3.77965124e-01, 8.07655663e-01,
        1.89148237e-01, 5.60100836e-01]])

In [30]:
import numpy as np

arr = np.arange(60).reshape(12, 5)
arr



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [31]:
arr[1,1]

np.int64(6)

In [37]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [38]:
arr[1,1]=100

In [39]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [42]:
arr[11,4]

np.int64(59)

In [43]:
arr[1,-1]

np.int64(9)

In [44]:
arr[-1,-1]

np.int64(59)

In [46]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [47]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [48]:
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [49]:
arr 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [50]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [51]:
arr[0,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [52]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [53]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [54]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [55]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [56]:
arr[0,1,1]=1000

In [57]:
arr[0,1,1]

np.int64(1000)

In [58]:
arr= np.array([1,5,6,9,2,3])

In [60]:
arr.sort()

In [61]:
arr

array([1, 2, 3, 5, 6, 9])

In [62]:
arr+2

array([ 3,  4,  5,  7,  8, 11])

In [63]:
arr-2

array([-1,  0,  1,  3,  4,  7])

In [64]:
arr/2

array([0.5, 1. , 1.5, 2.5, 3. , 4.5])

In [65]:
arr*2

array([ 2,  4,  6, 10, 12, 18])

In [66]:
arr1 =np.array([1,2,3,5])
arr2 =np.array([1,6,3,5])

In [67]:
arr1+arr2

array([ 2,  8,  6, 10])

In [68]:
arr1-arr2

array([ 0, -4,  0,  0])

In [69]:
arr1*arr2

array([ 1, 12,  9, 25])

In [70]:
arr1/arr2

array([1.        , 0.33333333, 1.        , 1.        ])